In [11]:
import numpy as np

In [29]:
b = np.array([[3,20,99],[-13,4.5,26],[0,-1,20],[5,78,-19]], dtype=list)
b

array([[3, 20, 99],
       [-13, 4.5, 26],
       [0, -1, 20],
       [5, 78, -19]], dtype=object)

In [30]:
b.shape

(4, 3)

In [31]:
b[2,1]

-1

In [33]:
print(b)
b[:,1]

[[3 20 99]
 [-13 4.5 26]
 [0 -1 20]
 [5 78 -19]]


array([20, 4.5, -1, 78], dtype=object)

In [118]:
b[1,:]

array([13, 30, 20], dtype=object)

In [35]:
b[1]

array([-13, 4.5, 26], dtype=object)

In [47]:
b[[0,1,1],[1,2,1]]

array([-10, -20, -30], dtype=object)

In [38]:
print(b)
b[[0,1,1],[1,2,1]]=[-10,-20,-30]
print(b)

[[3 20 99]
 [-13 4.5 26]
 [0 -1 20]
 [5 78 -19]]
[[3 -10 99]
 [-13 -30 -20]
 [0 -1 20]
 [5 78 -19]]


In [39]:
b

array([[3, -10, 99],
       [-13, -30, -20],
       [0, -1, 20],
       [5, 78, -19]], dtype=object)

In [41]:
b[b>0]

array([3, 99, 20, 5, 78], dtype=object)

In [120]:
print(b)
b[:,b[2]>=0]

[[3 -10 99]
 [13 30 20]
 [0 -1 20]
 [5 78 -19]]


array([[3, 99],
       [13, 20],
       [0, 20],
       [5, -19]], dtype=object)

In [45]:
b[2]>=0

array([ True, False,  True])

In [46]:
b[:,2]>=0

array([ True, False,  True, False])

In [48]:
b[b[:,2]>=0,:]

array([[3, -10, 99],
       [0, -1, 20]], dtype=object)

In [53]:
b[:,b[2]>=0]

array([[3, 99],
       [-13, -20],
       [0, 20],
       [5, -19]], dtype=object)

In [54]:
import math as m

In [55]:
b[1]=m.fabs(b[1])

TypeError: only size-1 arrays can be converted to Python scalars

In [56]:
print(b)
b[1]=np.abs(b[1])
b

[[3 -10 99]
 [-13 -30 -20]
 [0 -1 20]
 [5 78 -19]]


array([[3, -10, 99],
       [13, 30, 20],
       [0, -1, 20],
       [5, 78, -19]], dtype=object)

In [58]:
np.sum(b)

238

In [62]:
print(b)
np.sum(b,axis=0)

[[3 -10 99]
 [13 30 20]
 [0 -1 20]
 [5 78 -19]]


array([21, 97, 120], dtype=object)

In [63]:
print(b)
np.sum(b,axis=1)

[[3 -10 99]
 [13 30 20]
 [0 -1 20]
 [5 78 -19]]


array([92, 63, 19, 64], dtype=object)

In [64]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [121]:
np.linspace(start=1,stop=5,num=20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [71]:
np.random.randint(high=10,low=1,size=(3,3))

array([[7, 9, 4],
       [8, 8, 6],
       [1, 3, 3]])

In [74]:
np.random.random(size=(3,3))

array([[0.72132631, 0.35124127, 0.71034141],
       [0.96144569, 0.07271877, 0.70379812],
       [0.47208751, 0.86550335, 0.11791261]])

In [75]:
x=np.arange(10)

In [76]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.random.choice(x,6)

array([6, 3, 6, 4, 1, 6])

In [80]:
np.random.choice(x,6,replace=False)

array([1, 4, 2, 3, 0, 6])

In [94]:
y=np.random.choice(['a','b'],6)
y

array(['a', 'b', 'a', 'b', 'b', 'a'], dtype='<U1')

In [96]:
y=np.random.choice(['a','b'],1000)

In [97]:
np.unique(y,return_counts=True)

(array(['a', 'b'], dtype='<U1'), array([482, 518], dtype=int64))

In [116]:
y=np.random.choice(['a','b'],10,p=[0.8,0.2])

In [117]:
np.unique(y,return_counts=True)

(array(['a', 'b'], dtype='<U1'), array([9, 1], dtype=int64))

In [123]:
x=np.random.randint(high=100,low=12,size=(15))
x

array([79, 49, 67, 85, 26, 12, 53, 91, 83, 87, 66, 64, 56, 31, 34])

In [124]:
np.random.choice(x,5)

array([12, 85, 26, 66, 66])

In [125]:
x.sort()
x

array([12, 26, 31, 34, 49, 53, 56, 64, 66, 67, 79, 83, 85, 87, 91])

In [127]:
x=np.random.randint(high=100,low=12,size=(4,6))
x

array([[83, 85, 81, 97, 92, 60],
       [34, 35, 18, 82, 14, 75],
       [85, 60, 26, 12, 58, 61],
       [21, 19, 57, 55, 33, 61]])

In [128]:
x.sort()
x

array([[60, 81, 83, 85, 92, 97],
       [14, 18, 34, 35, 75, 82],
       [12, 26, 58, 60, 61, 85],
       [19, 21, 33, 55, 57, 61]])

In [132]:
x[:,2]

array([83, 34, 58, 33])

In [133]:
x[:,2].argsort()

array([3, 1, 2, 0], dtype=int64)

In [134]:
x[x[:,2].argsort(),:]

array([[19, 21, 33, 55, 57, 61],
       [14, 18, 34, 35, 75, 82],
       [12, 26, 58, 60, 61, 85],
       [60, 81, 83, 85, 92, 97]])

In [136]:
x=np.random.randint(high=100,low=12,size=(15))
x

array([42, 23, 95, 13, 49, 35, 46, 82, 56, 52, 78, 87, 16, 87, 90])

In [137]:
x.max()

95

In [138]:
x.min()

13

In [139]:
x.argmax()

2